# Generated by Django 6.0.4 on 2026-04-22 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.JSONField(default=dict, help_text='Store criteria name and mark mapping or just total')),
                ('submitted', models.BooleanField(default=False)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_marksheets', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marksheets', to='participants.member')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marksheets', to='programs.program')),
            ],
        ),
    ]
