# Generated by Django 6.0.4 on 2026-10-03 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judging', '0001_initial'),
        ('participants', '0005_callinglist_idx_call_prog_stat_call'),
        ('programs', '0018_alter_activitylog_action_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marksheet',
            index=models.Index(fields=['program', 'judge', 'submitted'], name='idx_mksht_prog_jdg_sub'),
        ),
    ]
