# Generated by Django 6.0.4 on 2026-06-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('programs', '0011_category_fest_program_fest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='programs.festsettings'),
        ),
    ]
