# Generated by Django 6.0.4 on 2026-06-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_alter_team_teamlead'),
        ('programs', '0011_category_fest_program_fest'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='fest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='programs.festsettings'),
        ),
        migrations.AlterField(
            model_name='callinglist',
            name='calling_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='chest_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('chest_no', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'fest')},
        ),
    ]
