# Generated by Django 6.0.4 on 2026-06-27 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_team_fest_alter_callinglist_calling_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callinglist',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callinglist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callinglist',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calling_lists', to='participants.member'),
        ),
        migrations.AlterField(
            model_name='callinglist',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('absent', 'Absent'), ('present', 'Present')], default='waiting', max_length=15),
        ),
    ]
