# Generated by Django 6.0.4 on 2026-10-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_callinglist_called_at_callinglist_created_at_and_more'),
        ('programs', '0018_alter_activitylog_action_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='callinglist',
            index=models.Index(fields=['program', 'status', 'called_at'], name='idx_call_prog_stat_call'),
        ),
    ]
