# Generated by Django 6.0.4 on 2026-04-22 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chest_prefix', models.IntegerField(help_text='e.g. 100 for 100 series')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='FestSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fest_name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='fest_logos/')),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('point_system', models.JSONField(default=dict, help_text='ex: {"1st": 5, "2nd": 3, "3rd": 1}')),
            ],
            options={
                'verbose_name_plural': 'Fest Settings',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('max_marks', models.IntegerField(default=100)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='programs.category')),
            ],
        ),
        migrations.CreateModel(
            name='PosterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='poster_templates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poster_template', to='programs.program')),
            ],
        ),
    ]
