# Generated by Django 6.0.4 on 2026-04-22 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='judges',
            field=models.ManyToManyField(blank=True, limit_choices_to={'userprofile__role': 'judge'}, related_name='assigned_programs', to=settings.AUTH_USER_MODEL),
        ),
    ]
