# Generated by Django 6.0.4 on 2026-04-24 05:51

import programs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_program_judges'),
    ]

    operations = [
        migrations.AddField(
            model_name='postertemplate',
            name='config',
            field=models.JSONField(default=programs.models.default_poster_config),
        ),
    ]
