# Generated by Django 6.0.4 on 2026-04-24 05:55

import programs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_postertemplate_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPosterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='poster_templates/')),
                ('config', models.JSONField(default=programs.models.default_poster_config)),
            ],
        ),
    ]
