# Generated by Django 6.0.4 on 2026-04-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_globalpostertemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='participant_limit',
            field=models.IntegerField(default=0, help_text='0 for unlimited'),
        ),
    ]
