# Generated by Django 6.0.2 on 2026-05-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_program_participant_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='participant_limit',
            field=models.IntegerField(default=0, help_text='Maximum participants per team (0 for unlimited)'),
        ),
    ]
