# Generated by Django 6.0.2 on 2026-05-20 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_alter_program_participant_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramGradeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=50)),
                ('min_marks', models.FloatField()),
                ('points', models.IntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_settings', to='programs.program')),
            ],
            options={
                'ordering': ['-min_marks'],
                'unique_together': {('program', 'grade_name')},
            },
        ),
    ]
