# Generated by Django 6.0.2 on 2026-05-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_programgradesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.IntegerField(default=5, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='program',
            name='point_weightage',
            field=models.IntegerField(default=1, help_text='Point weightage multiplier'),
        ),
        migrations.AddField(
            model_name='program',
            name='stage_type',
            field=models.CharField(choices=[('onstage', 'On stage'), ('offstage', 'Offstage')], default='onstage', max_length=10),
        ),
        migrations.AddField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('single', 'Single'), ('group', 'Group')], default='single', max_length=10),
        ),
    ]
