# Generated by Django 6.0.2 on 2026-05-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_program_duration_program_point_weightage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='point_weightage',
        ),
        migrations.AddField(
            model_name='program',
            name='point_weightage_1st',
            field=models.IntegerField(default=1, help_text='Point weightage multiplier for 1st rank'),
        ),
        migrations.AddField(
            model_name='program',
            name='point_weightage_2nd',
            field=models.IntegerField(default=1, help_text='Point weightage multiplier for 2nd rank'),
        ),
        migrations.AddField(
            model_name='program',
            name='point_weightage_3rd',
            field=models.IntegerField(default=1, help_text='Point weightage multiplier for 3rd rank'),
        ),
    ]
