# Generated by Django 6.0.4 on 2026-06-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_remove_program_point_weightage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='group_size',
            field=models.IntegerField(blank=True, default=1, help_text='Number of people in group program', null=True),
        ),
    ]
