# Generated by Django 6.0.4 on 2026-06-27 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_program_group_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='programs.festsettings'),
        ),
        migrations.AddField(
            model_name='program',
            name='fest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='programs.festsettings'),
        ),
    ]
