# Generated by Django 6.0.4 on 2026-07-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='festsettings',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description shown on the public home page'),
        ),
    ]
