# Generated by Django 6.0.4 on 2026-07-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0013_festsettings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='festsettings',
            name='dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='stage',
            name='type',
            field=models.CharField(choices=[('onstage', 'On stage'), ('offstage', 'Offstage')], default='onstage', max_length=10),
        ),
    ]
