# Generated by Django 6.0.2 on 2026-08-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_festsettings_dates_stage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='festsettings',
            name='publish_team_standings',
            field=models.BooleanField(default=True, help_text='Toggle public visibility of overall team standings'),
        ),
    ]
