# Generated by Django 6.0.2 on 2026-08-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_festsettings_publish_team_standings'),
    ]

    operations = [
        migrations.AddField(
            model_name='festsettings',
            name='published_standings_limit',
            field=models.IntegerField(default=0, help_text='Limit public standings calculation to first N published programs. 0 for all.'),
        ),
    ]
