# Generated by Django 6.0.4 on 2026-08-18 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_festsettings_published_standings_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('action_type', models.CharField(choices=[('result_published', 'Result Published'), ('result_unassigned', 'Result Updated'), ('marks_submitted', 'Marksheet Submitted'), ('lot_called', 'Lot Called'), ('lot_respun', 'Lot Respun'), ('member_registered', 'Member Registered'), ('member_assigned', 'Member Assigned'), ('program_created', 'Program Created'), ('program_scheduled', 'Program Scheduled'), ('stage_created', 'Stage Created'), ('team_created', 'Team Created'), ('judge_assigned', 'Judge Assigned'), ('user_created', 'User Created'), ('settings_updated', 'Fest Settings Updated')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_model', models.CharField(blank=True, max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='programs.festsettings')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
