# Generated by Django 6.0.4 on 2026-10-03 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('result_published', 'Result Published'), ('result_unassigned', 'Result Updated'), ('marks_submitted', 'Marksheet Submitted'), ('lot_called', 'Lot Called'), ('lot_respun', 'Lot Respun'), ('member_registered', 'Member Registered'), ('member_assigned', 'Member Assigned'), ('member_deleted', 'Member Deleted'), ('program_created', 'Program Created'), ('program_scheduled', 'Program Scheduled'), ('program_deleted', 'Program Deleted'), ('stage_created', 'Stage Created'), ('stage_deleted', 'Stage Deleted'), ('team_created', 'Team Created'), ('team_deleted', 'Team Deleted'), ('judge_assigned', 'Judge Assigned'), ('user_created', 'User Created'), ('user_deleted', 'User Deleted'), ('settings_updated', 'Fest Settings Updated')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['fest', '-created_at'], name='idx_actlog_fest_created'),
        ),
    ]
